### ISSUE TITLE
Fails on python3 due to unicode-related errors

### ISSUE THREAD

**Issue by dagwieers** [cmprescott/ansible-xml#116]
During the effort of upstreaming this module, we found that the module fails on Python 3 due to unicode-related problems.

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_xi97wmbt/ansible_module_xml.py", line 732, in <module>
    main()
  File "/tmp/ansible_xi97wmbt/ansible_module_xml.py", line 658, in main
    add_children = decode(module.params['add_children'])
  File "/tmp/ansible_xi97wmbt/ansible_module_xml.py", line 608, in decode
    if not value or isinstance(value, unicode):
NameError: name 'unicode' is not defined

fatal: [testhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_xi97wmbt/ansible_module_xml.py\", line 732, in <module>\n    main()\n  File \"/tmp/ansible_xi97wmbt/ansible_module_xml.py\", line 658, in main\n    add_children = decode(module.params['add_children'])\n  File \"/tmp/ansible_xi97wmbt/ansible_module_xml.py\", line 608, in decode\n    if not value or isinstance(value, unicode):\nNameError: name 'unicode' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

**Comment by dagwieers** [comment]
This is now fixed in the upstreamed module.
