### ISSUE TITLE
Failure when 'file' not specified (while using xmlstring)

### ISSUE THREAD

**Issue by stevemendes** [cmprescott/ansible-xml#50]
in library/xml line 337:

    xml_file = os.path.expanduser(module.params['file'])

This fails when 'xmlstring' is used for input and no 'file' is specified.

**Comment by martinboy** [comment]
Here is the detailed exception log
```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/martin/.ansible/tmp/ansible-tmp-1463119637.43-195335344731674/xml", line 2396, in <module>
    main()
  File "/Users/martin/.ansible/tmp/ansible-tmp-1463119637.43-195335344731674/xml", line 327, in main
    xml_file = os.path.expanduser(module.params['file'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'


```
